server:
  port: 8080


spring:
  security:
    oauth2:
      client:
        registration:
          my-client:
            client-id: gateway-client
            client-secret: secret
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: openid, profile, email
        provider:
          my-provider:
            issuer-uri: ${AUTH_SERVICE_URL:http://localhost:4006}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://localhost:4006}
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: notes-service
              uri: ${NOTES_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/notes/**       # matches /api/notes/*
              filters:
                - StripPrefix=1            # removes /api from forwarded path

            - id: test
              uri: https://www.google.com   # use Google as reachable test
              predicates:
                - Path=/test/**
              filters:
                - StripPrefix=1