server:
  port: ${SERVER_PORT:4007}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: notes-service
              uri: http://notes-service:8082
              predicates:
                - Path=/api/notes/**
              filters:
                - StripPrefix=1
            - id: test
              uri: https://www.google.com   # use Google as reachable test
              predicates:
                - Path=/test/**
              filters:
                - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://host.docker.internal:4000/oauth2/jwks

#  cloud:
#    gateway:
#      routes:
#        - id: auth-service
#          uri: http://localhost:4000
#          predicates:
#            - Path=/auth/**
#            - Path=/oauth2/**
#          filters: []
          # removes /api from forwarded path
#
#        - id: test
#          uri: https://www.google.com   # use Google as reachable test
#          predicates:
#            - Path=/test/**
#          filters:
#            - StripPrefix=1