server:
  port: 8080


spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: notes-service
              uri: ${NOTES_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/notes/**       # matches /api/notes/*
              filters:
                - StripPrefix=1            # removes /api from forwarded path

            - id: test
              uri: https://www.google.com   # use Google as reachable test
              predicates:
                - Path=/test/**
              filters:
                - StripPrefix=1