server:
  port: 8080


spring:
  spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: ${AUTH_SERVICE_URL:http://auth-service:4006}/oauth2/jwks
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://localhost:4006}
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: notes-service
              uri: ${NOTES_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/notes/**       # matches /api/notes/*
              filters:
                - StripPrefix=1            # removes /api from forwarded path

            - id: test
              uri: https://www.google.com   # use Google as reachable test
              predicates:
                - Path=/test/**
              filters:
                - StripPrefix=1